export const TRANSACTION_CATEGORY_LABELS = {
  EDUCATION: "Educação",
  ENTERTAINMENT: "Entretenimento",
  FOOD: "Alimentação",
  HEALTH: "Saúde",
  HOUSING: "Moradia",
  OTHER: "Outros",
  SALARY: "Salário",
  TRANSPORTATION: "Transporte",
  UTILITY: "Utilidades",
};

export const TRANSACTION_CATEGORY_OPTIONS = [
  { value: "EDUCATION", label: TRANSACTION_CATEGORY_LABELS.EDUCATION },
  { value: "ENTERTAINMENT", label: TRANSACTION_CATEGORY_LABELS.ENTERTAINMENT },
  { value: "FOOD", label: TRANSACTION_CATEGORY_LABELS.FOOD },
  { value: "HEALTH", label: TRANSACTION_CATEGORY_LABELS.HEALTH },
  { value: "HOUSING", label: TRANSACTION_CATEGORY_LABELS.HOUSING },
  { value: "OTHER", label: TRANSACTION_CATEGORY_LABELS.OTHER },
  { value: "SALARY", label: TRANSACTION_CATEGORY_LABELS.SALARY },
  {
    value: "TRANSPORTATION",
    label: TRANSACTION_CATEGORY_LABELS.TRANSPORTATION,
  },
  { value: "UTILITY", label: TRANSACTION_CATEGORY_LABELS.UTILITY },
];
